let IMAGES = {
    appleLogo: require('./Apple.png'),
    phone8: require('./applePhone.png'),
    beautyCream: require('./beauty.png'),
    cherry: require('./cherry.png'),
    cookie: require('./cookie-g1ad0e45b6_1280.png'),
    spoon: require('./cooking-spoon-159122_1280.png'),
    vegitables: require('./daily.png'),
    jwellary: require('./fashion.png'),
    flowers: require('./flowers.png'),
    fridge: require('./fridge-gad8610bd9_1280.png'),
    phone7: require('./frontGalaxy.png'),
    phone6: require('./galaxy.png'),
    phone5: require('./galaxyS.png'),
    phone4: require('./galaxym13.png'),
    phone3: require('./galaxym33.png'),
    icecream2: require('./ice-cream-gec0d88d49_1280.png'),
    playStore: require('./image 10.png'),
    appStore: require('./image 11.png'),
    mango: require('./mango.png'),
    phone2: require('./mi.png'),
    miLogo: require('./miLogo.png'),
    microwave: require('./microwave-g84e57cb34_1280.png'),
    nailpolish4: require('./nail-polish-g7b44958b3_1280.png'),
    nailpolish3: require('./nail-polish-g8b77ddea1_1280.png'),
    nailpolish2: require('./nail-polish-g8b77ddea1_1280.png'),
    nailpolish1: require('./nail-polish-gbcd2d9a1d_1280.png'),
    phone1: require('./narzp.png'),
    icecream: require('./popsicle-gd111b64aa_1280.png'),
    realmeLogo: require('./realme.png'),
    smartwatch: require('./smartWatch.png'),
    smartwatch2: require('./smartWatch2.png'),
    smartwatch3: require('./smartWatch3.png'),
    smartwatch4: require('./smartWatch4.png'),
    smartwatch5: require('./smartWatch5.png'),
    sofa: require('./sofa.png'),
    berry: require('./staraw.png'),
    starbucks1: require('./thumb1.png'),
    starbucks2: require('./thumb2.png'),
    starbucks3: require('./thumb3.png'),
    washingMachine: require('./washing.png')
}
export default IMAGES
